client_config_backend: file
client_config:
  client_id: 88455495896-bv11ub6hvh5at1fpn7nfnagakrr0m26c.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install